export const metadata = {
  title: "Disclaimer – AI Sports Guru",
  description:
    "Important legal disclaimers about the use of AI Sports Guru’s predictions.",
};

export default function DisclaimerPage() {
  return (
    <div className="max-w-3xl mx-auto py-12 space-y-6">
      <h1 className="text-3xl font-bold text-secondary">Disclaimer</h1>
      <p className="text-gray-700">
        AI Sports Guru provides sports betting predictions generated by machine
        learning and AI technologies. These predictions are for entertainment
        purposes only and are not guaranteed to be accurate or successful.
      </p>
      <p className="text-gray-700">
        Users are solely responsible for their betting decisions. AI Sports Guru
        and its creators are not liable for any financial losses or damages
        incurred from the use of the platform.
      </p>
      <p className="text-gray-700">
        Please gamble responsibly and adhere to your local laws and regulations.
        If you or someone you know has a gambling problem, please seek help from
        a professional organization.
      </p>
    </div>
  );
}
