platform :ios, '17.0'
ENV['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
begin
  require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
rescue LoadError
  Pod::UI.warn '@react-native-community/cli-platform-ios native_modules not found; continuing (Expo autolinking will handle modules)'
end
require_relative '../node_modules/expo/scripts/autolinking'

target 'AISportsGuru' do
  use_expo_modules!

  config = defined?(use_native_modules!) ? use_native_modules! : { reactNativePath: '../node_modules/react-native' }
  use_react_native!(
    :path => config[:reactNativePath] || '../node_modules/react-native',
    :hermes_enabled => true
  )

  # Important for RN Reanimated linking
  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |c|
        c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      end
    end
  end
end
