platform :ios, '17.0'
ENV['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
begin
  require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
rescue LoadError
  Pod::UI.warn '@react-native-community/cli-platform-ios native_modules not found; continuing (Expo autolinking will handle modules)'
end
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")

target 'AISportsGuru' do
  use_expo_modules!

  config = defined?(use_native_modules!) ? use_native_modules! : { reactNativePath: '../node_modules/react-native' }
  use_react_native!(
    :path => config[:reactNativePath] || '../node_modules/react-native',
    :hermes_enabled => true
  )

  post_install do |installer|
    react_native_post_install(installer)
    # Force 17.0 across the Pods project (doesn't affect resolver, but keeps build settings sane)
    installer.pods_project.build_configurations.each { |bc| bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0' }
    installer.pods_project.targets.each do |t|
      t.build_configurations.each { |c| c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0' }
    end
  end
end
