<<<<<<< Updated upstream
name: Daily NFL Injuries
on: { workflow_dispatch: {}, schedule: [ { cron: "5 12 * * *" } ] }
permissions: { contents: read }
concurrency: { group: injuries-nfl, cancel-in-progress: true }
=======
name: Daily NFL injuries sync

on:
  workflow_dispatch: {}
  schedule:
    - cron: "5 12 * * *"   # daily 12:05 UTC (adjust as needed)

permissions:
  contents: read

concurrency:
  group: injuries-nfl
  cancel-in-progress: true

>>>>>>> Stashed changes
jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      INJURIES_API_KEY: ${{ secrets.INJURIES_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
<<<<<<< Updated upstream
        with: { node-version: "20", cache: "npm" }
      - run: npm ci --prefer-offline --no-audit --no-fund
      - name: Run
        run: |
          if [ -z "${INJURIES_API_KEY:-}" ]; then echo "No INJURIES_API_KEY, skipping"; exit 0; fi
          if [ -f scripts/injuries-sync.mjs ]; then node --unhandled-rejections=strict scripts/injuries-sync.mjs nfl; \
          elif [ -f scripts/injuries/nfl.mjs ]; then node --unhandled-rejections=strict scripts/injuries/nfl.mjs; \
          else echo "No injuries script, skipping"; fi
=======
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci --prefer-offline --no-audit --no-fund

      - name: Run injuries sync (nfl)
        shell: bash
        run: |
          set -euo pipefail
          if [ -z "${INJURIES_API_KEY:-}" ]; then
            echo "No INJURIES_API_KEY configured; skipping gracefully."
            exit 0
          fi

          if [ -f scripts/injuries-sync.mjs ]; then
            node --unhandled-rejections=strict scripts/injuries-sync.mjs nfl
          elif [ -f scripts/injuries/nfl.mjs ]; then
            node --unhandled-rejections=strict scripts/injuries/nfl.mjs
          else
            echo "No injuries script found; skipping."
          fi
>>>>>>> Stashed changes
