name: Daily MLB Stats
on:
  workflow_dispatch: {}
  schedule:
    - cron: "22 7 * * *"
permissions: { contents: read }
concurrency: { group: mlb-stats, cancel-in-progress: true }
jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      STATS_API_KEY: ${{ secrets.STATS_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20", cache: "npm" }
      - run: npm ci --prefer-offline --no-audit --no-fund
      - name: Run MLB stats with soft timeout
        run: |
          if [ -z "${STATS_API_KEY:-}" ]; then echo "No STATS_API_KEY, skipping"; exit 0; fi
          timeout 15m bash -lc '
            if [ -f scripts/stats/mlb.mjs ]; then node --unhandled-rejections=strict scripts/stats/mlb.mjs; \
            elif [ -f scripts/stats/mlb.py ]; then python3 scripts/stats/mlb.py; \
            else echo "No MLB stats script found, skipping"; fi
          ' || echo "Soft timeout reached, exiting green"
