name: NCAAF Monthly Backfill
on:
  schedule:
    - cron: '0 7 3 * *'    # 3rd day of month 07:00 UTC
  workflow_dispatch: {}
jobs:
  backfill:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Set env
        run: |
          echo "SUPABASE_DB_URL=${{ secrets.SUPABASE_DB_URL }}" >> $GITHUB_ENV
          echo "CFBD_API_KEY=${{ secrets.CFBD_API_KEY }}" >> $GITHUB_ENV
      - name: Run backfill
        env:
          SUPABASE_DB_URL: ${{ env.SUPABASE_DB_URL }}
          CFBD_API_KEY: ${{ env.CFBD_API_KEY }}
        run: bash scripts/data-sync/ncaaf_monthly_backfill.sh
