name: NCAAF Health Check
on:
  workflow_dispatch: {}
  schedule:
    - cron: "15 * * * *"
permissions: { contents: read }
concurrency: { group: ncaaf-health, cancel-in-progress: true }
jobs:
  health:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
    steps:
      - name: Probe counts via Supabase REST
        run: |
          set -e
          if [ -z "${NEXT_PUBLIC_SUPABASE_URL:-}" ] || [ -z "${SUPABASE_SERVICE_ROLE_KEY:-}" ]; then
            echo "Missing Supabase env, failing"
            exit 1
          fi
          BASE="${NEXT_PUBLIC_SUPABASE_URL%/}/rest/v1"
          NOW=$(date -u +%FT%TZ)
          TO=$(date -u -d "+7 days" +%FT%TZ)
          GAMES_CNT=$(curl -s "${BASE}/games?select=game_id&sport=eq.ncaaf&start_time=gte.${NOW}&start_time=lte.${TO}" \
            -H "apikey: ${SUPABASE_SERVICE_ROLE_KEY}" -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" | jq "length")
          PREDS_CNT=$(curl -s "${BASE}/mat_games_with_odds_predictions?select=game_id&sport=eq.ncaaf&start_time=gte.${NOW}&start_time=lte.${TO}" \
            -H "apikey: ${SUPABASE_SERVICE_ROLE_KEY}" -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" | jq "length" || echo 0)
          echo "gamesCnt=${GAMES_CNT} predsCnt=${PREDS_CNT}"
          if [ "${GAMES_CNT}" -eq 0 ] || [ "${PREDS_CNT}" -eq 0 ]; then
            echo "Health not ok"
            exit 2
          fi
          echo "Health ok"
