name: NCAAB Roster Refresh

on:
  workflow_dispatch: {}
  # Optional: run weekly in preseason
  schedule:
    - cron: "30 13 * * 1"

jobs:
  ncaab-roster-refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r scripts/ncaab/requirements.txt

      - name: Refresh rosters
        env:
          PYTHONPATH: ${{ github.workspace }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          . .venv/bin/activate
          python scripts/ncaab/ncaab_roster_refresh.py
