name: Weekly NCAAF sync
on:
  schedule: [{ cron: "0 13 * * SUN" }]  # Sundays 13:00 UTC ~ 06:00 PT
  workflow_dispatch: {}
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Set env
        run: |
          echo "SUPABASE_DB_URL=${{ secrets.SUPABASE_DB_URL }}" >> $GITHUB_ENV
          echo "CFBD_API_KEY=${{ secrets.CFBD_API_KEY }}" >> $GITHUB_ENV
          echo "SEASONS=$(date +%Y)" >> $GITHUB_ENV
      - name: Run sync
        env:
          SUPABASE_DB_URL: ${{ env.SUPABASE_DB_URL }}
          CFBD_API_KEY: ${{ env.CFBD_API_KEY }}
          SEASONS: ${{ env.SEASONS }}
        run: bash scripts/data-sync/ncaaf_sync.sh
