name: Predict Cron

on:
  schedule:
    - cron: "*/20 * * * *"   # NFL frequent (every 20 min, UTC)
    - cron: "0 * * * *"      # NCAAF hourly
    - cron: "15 * * * *"     # MLB hourly
  workflow_dispatch: {}       # allow manual runs

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - name: NFL (14d)
        run: |
          curl -fsS --max-time 25 "https://aisportsguru.com/api/predict/run?league=nfl&days=14&store=1" || true

      - name: NCAAF (14d)
        run: |
          curl -fsS --max-time 25 "https://aisportsguru.com/api/predict/run?league=ncaaf&days=14&store=1" || true

      - name: MLB (7d)
        run: |
          curl -fsS --max-time 25 "https://aisportsguru.com/api/predict/run?league=mlb&days=7&store=1" || true

    # Avoid overlapping runs if a previous one is still running
    concurrency:
      group: predict-cron
      cancel-in-progress: false
