name: Daily Predictions Refresh

on:
  schedule:
    # Every day at 5:00 UTC (10 PM PT / 1 AM ET)
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Call NFL predictions
        run: curl -s "${{ secrets.SITE_URL }}/api/predict/run?league=nfl&days=14&store=1"

      - name: Call NCAAF predictions
        run: curl -s "${{ secrets.SITE_URL }}/api/predict/run?league=ncaaf&days=14&store=1"

      - name: Call MLB predictions
        run: curl -s "${{ secrets.SITE_URL }}/api/predict/run?league=mlb&days=14&store=1"
